### ISSUE TITLE
Connect PHP to mySQL

### ISSUE THREAD

**Issue by sukotyas** [mathewpeterson/docker-nginx-mysql-php#1]
Hi Mathew,
So far this is the best docker-compose.yml file that I found. However, I'm having difficulties in connecting my app with mysql. I got this error:
`Fatal error: Call to undefined function mysql_connect()`
Seems like mysql extension for phpfpm hasn't been added. How to install the related php extension here?

**Comment by mathewpeterson** [comment]
That's most likely because the mysql library has been deprecated. You should be using PDO now. 

In any case, you would need to extend the base php:5.6-fpm container to add in the extension.

**Comment by sukotyas** [comment]
I know. What I mean is the installation of the required php extensions. I have solved this problem though, by combining both Dockerfile and docker-compose. I built an image that install PHP and all of required extensions in a Dockerfile, then I loaded the image in docker-compose.yml file.
